from selenium.webdriver.common.by import By


class Locators:
    class DirectChatPage:
        DIRECT_CHAT_TAB = (By.XPATH, "//div[@class='im-ct-menu-title im-ct-contacts-header' and text()='Direct Chat']")
        OVERLAY_SHOW_ACTIONS = (By.CLASS_NAME, "cdk-overlay-pane")
        DC_TAB_LAYOUT_AREA = (By.XPATH, "//*[contains(@class, 'im-td-directchattablayout-body')]")
        MESSAGES_AREA = (By.XPATH, "//*[contains(@class, 'im-da-ch-marginTop')]")
        MESSAGE_LISTS = (By.CSS_SELECTOR, "[class*='im-da-ch-msg-text ng-star-inserted']")
        DIRECT_CHAT_AREA = (By.CLASS_NAME, "im-ct-contacts")
        PINNED_CONTACTS_AREA = (By.CLASS_NAME, "im-ct-contacts-pinned")
        DC_CONTACT_DIRECT_CHAT = (By.CSS_SELECTOR, f"[class*='{'im-ct-pinnedcontacts-contactcontainer'}']")
        DC_CONTACT_NAME_DIRECT_CHAT = (By.CSS_SELECTOR,
                                       f"[class*='{'im-sc-participantName im-sc-participant-myChatContact'}']")
        DC_CONTACT_GREEN_INDICATOR_DIRECT_CHAT = (By.CSS_SELECTOR, f"[class*='{'im-ct-pinnedcontacts-status ng-star'}']")
        DC_CONTACTS_UNDER_DIRECT_CHAT = (By.CLASS_NAME, "im-ct-contacts-pinned")
        DC_CONTACTS_AREA = (By.CSS_SELECTOR, f"[class*='{'im-ct-pinnedcontacts-contactcontainer'}']")
        DC_CONTACT_NAME_AREA = (By.CSS_SELECTOR, f"[class*='{'im-sc-participant-myChatContact'}']")
        DC_HEADER = (By.XPATH, "//*[contains(@class, 'im-dctab-headerroot')]")
        CHAT_EDITOR = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-textarea editable-element'}']")
        DC_TAB_LAYOUT = (By.XPATH, "//*[contains(@class, 'im-td-directchattablayout-body')]")
        DC_MESSAGE_AREA = (By.XPATH, "//*[contains(@class, 'im-da-ch-marginTop')]")
        DC_MESSAGE = (By.CSS_SELECTOR, "[class*='im-da-ch-msg-text ng-star-inserted']")
        DC_FILE = (By.CSS_SELECTOR, "[class*='attachImgIcon-fileName']")
        SVG_ICONS = (By.TAG_NAME, "svg")
        SVG_ICON_CONTACT_ROW_ACTION = (By.TAG_NAME, "im-sc-svgicon")
        BLOCK_UI_DC = (By.XPATH, "//*[contains(@class, 'im-da-ch-dc-blockContactContainer')]")
        REPLY_ICON_DC_MESSAGE = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-hoverActionIcon'}']")
        GREEN_INDICATOR_STATUS_ICON = (By.CSS_SELECTOR, f"[class*='{'im-ct-pinnedcontacts-status'}']")
        UNREAD_NEW_MESSAGES_STRIP = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-unreadStrip'}']")
        FILE_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-td-overlayDynamicContent'}']")
        FILE_MAIN_OVERLAY = (By.CLASS_NAME, "im-td-detailsoverlay-container")
        CLOSE_ICON_OVERLAY = (By.CSS_SELECTOR, "[class*='im-td-overlayClose-icon']")
        NO_PREVIEW_AVAILABLE = (By.CSS_SELECTOR, f"[class*='{'im-da-th-singeton-filePreviewText'}']")
        FILE_DOWNLOAD_BUTTON = (By.CSS_SELECTOR, f"[class*='{'im-da-th-singletonDownloadFileBtn'}']")
        IFRAME_ELEMENT_CLASS = (By.CSS_SELECTOR, f"[class*='{'im-da-th-singletonfile-iframe'}']")
        IFRAME_ELEMENT_PREPARING_CLARITI_VIEWER = (By.CSS_SELECTOR, "[class*='fv-downloadingAnimationDiv']")
        IFRAME_ELEMENT_FILE_CONTAINER = (By.CSS_SELECTOR, "[class*='fv-fileContainer']")
        UNSUPPORTED_FILE_AREA = (By.CSS_SELECTOR, f"[class*='{'im-da-th-unsupportedFile'}']")
        DOWNLOAD_BUTTON_FILE_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-da-th-singletonDownloadFileBtn'}']")
        INPUT_AREA = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-inputcontainer'}']")
        REFERENCE_STRIP_AREA = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-refmsg'}']")
        REFERENCE_STRIP_CONTAINER = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-refmsg-rootcontainer'}']")
        REFERENCE_STRIP_MESSAGE_TEXT = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-refmsg-textcontainer'}']")
        REFERENCE_STRIP_FILE_TEXT = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-refmsg-filename'}']")
        SHOW_ACTIONS_ICON = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-messageActionIcon'}']")
        REPLY_BUTTON_SHOW_ACTION = (By.XPATH, "//button/span/span[contains(text(), 'Reply')]")
        FORWARD_BUTTON_SHOW_ACTION = (By.XPATH, "//button/span/span[contains(text(), 'Forward')]")
        COPY_BUTTON_SHOW_ACTION = (By.XPATH, "//button/span/span[contains(text(), 'Copy')]")
        FORWARD_BUTTON_DIALOG = (By.XPATH, "//button/span[contains(text(), 'Forward')]")
        FORWARDED_STRIP_MESSAGE = (By.CSS_SELECTOR, f"[class='{'im-da-ch-forwardedLabel'}']")
        GET_NAME_MESSAGE = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-msg-name'}']")
        GET_TIME_MESSAGE = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-msg-time'}']")
        GET_TIME_HOVER_MESSAGE = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-msgNameNotShown'}']")
        SCROLL_TO_BOTTOM_ICON = (By.CSS_SELECTOR, "[class*='im-da-ch-dc-arrowWithNewMsgCnt']")
        NEW_MESSAGE_STRIP = (By.CSS_SELECTOR, "[class*='im-da-ch-unreadStrip']")
        MAT_ICONS = (By.CSS_SELECTOR, f"[class*='{'mat-icon notranslate material-icons'}']")
        SEARCH_TEXT_BOX_CONTAINER = (By.CSS_SELECTOR, f"[class='{'im-da-ch-dc-search'}']")
        SEARCH_INPUT_TEXTBOX = (By.TAG_NAME, "input")
        SEARCH_ICON = (By.CSS_SELECTOR, f"[class='{'im-da-ch-dc-searchActions'}']")
        SEARCH_MESSAGES_FOUND_HINT = (By.CSS_SELECTOR, f"[class*='{'bottom-align hint'}']")
        SEARCH_LOADING_ICON = (By.CSS_SELECTOR,f"[class='{'im-se-search-inProgress'}']")


    class CalendarPage:
        CALENDAR_TAB = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Calendar']")
        HEADER_ICON_AREA = (By.CSS_SELECTOR, f"[class*='{'im-tc-startnewcommstrip'}']")
        TODO_HEADER_ICON = (By.XPATH, ".//*[contains(text(), 'To-Do')]")
        EVENT_HEADER_ICON = (By.XPATH, ".//*[contains(text(), 'Event')]")
        CALL_HEADER_ICON = (By.XPATH, ".//*[contains(text(), 'Call')]")
        OVERLAY_PANE = (By.CSS_SELECTOR, f"[class*='{'cdk-overlay-pane'}']")
        OVERLAY_CONTAINER = (By.CSS_SELECTOR, f"[class*='{'cdk-overlay-container'}']")
        CALENDAR_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-td-cdrive-detailsOverlay'}']")
        CLOSE_ICON_OVERLAY = (By.CSS_SELECTOR, "[class*='im-td-overlayClose-icon']")
        DISCARD_YES_BUTTON = (By.XPATH, "//button[contains(., 'Yes')]")
        DISCARD_NO_BUTTON = (By.XPATH, "//button[contains(., 'No')]")
        REASON_TO_DO = (By.CSS_SELECTOR, "[class*='im-td-todo-reason']")
        REASON_REMIND_ME = (By.XPATH,
                            "//div[contains(@class, 'mat-select-panel-wrap')]//div//div//mat-option[contains(@class, 'material-select-option')]//span[text()=' Remind me about ']")
        REASON_SCHEDULE_CHAT = (By.XPATH,
                                "//div[contains(@class, 'mat-select-panel-wrap')]//div//div//mat-option[contains(@class, 'material-select-option')]//span[text()=' Schedule a chat ']")
        REASON_COMPOSE_MAIL = (By.XPATH,
                               "//div[contains(@class, 'mat-select-panel-wrap')]//div//div//mat-option[contains(@class, 'material-select-option')]//span[text()=' Compose new mail ']")
        REASON_SCHEDULE_CALL = (By.XPATH,
                                "//div[contains(@class, 'mat-select-panel-wrap')]//div//div//mat-option[contains(@class, 'material-select-option')]//span[text()=' Schedule a call ']")
        SUBJECT_TEXT_BOX = (By.XPATH,
                            "//mat-form-field[contains(@class, 'im-td-todo-subject')]//div//div//div//input[contains(@class, 'mat-input-element')]")
        DATE_PICKER_ICON = (By.CSS_SELECTOR, f"[class*='{'im-sh-date-area'}']")
        TIME_PICKER_ICON = (By.CSS_SELECTOR, f"[class*='{'im-uc-dateComponent-timecontrol'}']")
        SHOW_OPTIONAL_FIELDS_TEXT = (By.CSS_SELECTOR, f"[class*='{'im-td-todo-advanced'}']")
        DESCRIPTION_TEXT_BOX = (By.CSS_SELECTOR, f"[class*='{'im-td-description-textarea'}']")
        REMIND_ME_DROP_DOWN = (By.XPATH, "//mat-form-field[contains(@class, 'im-td-todo-reminder')]//mat-select")
        REMIND_ME_OPTION_LISTS = (By.CSS_SELECTOR, f"[class*='{'ps--active-y'}']")
        REMIND_ME_OPTION_ITEM = (By.CSS_SELECTOR, f"[class*='{'material-select-option'}']")
        REMIND_ME_OPTION_ITEM_TEXT = (By.CSS_SELECTOR, f"[class*='{'mat-option-text'}']")
        SCHEDULE_TODO_BUTTON = (By.CSS_SELECTOR, f"[class*='{'im-cm-footersenddiscard-SendBtn'}']")
        SCHEDULED_FILTER_BUTTON = (By.XPATH,
                                   "//div[contains(@class, 'im-td-definedfilter-container')]//button[contains(@class, 'im-td-filterbtn')]//span[text()=' Scheduled ']")
        COMPLETED_FILTER_BUTTON = (By.XPATH,
                                   "//div[contains(@class, 'im-td-definedfilter-container')]//button[contains(@class, 'im-td-filterbtn')]//span[text()=' Completed ']")
        MONTHLY_FILTER_BUTTON = (By.XPATH,
                                 "//div[contains(@class, 'im-td-definedfilter-container')]//button[contains(@class, 'im-td-filterbtn')]//span[text()=' Monthly ']")
        WEEKLY_FILTER_BUTTON = (By.XPATH,
                                "//div[contains(@class, 'im-td-definedfilter-container')]//button[contains(@class, 'im-td-filterbtn')]//span[text()=' Weekly ']")
        DAILY_FILTER_BUTTON = (By.XPATH,
                               "//div[contains(@class, 'im-td-definedfilter-container')]//button[contains(@class, 'im-td-filterbtn')]//span[text()=' Daily ']")

    class ContactsPage:
        CLARITI_FULL_VIEW = (By.CSS_SELECTOR, f"[class*='im-app-left-splitter']")
        DIRECT_CHAT_TAB = (By.XPATH, "//div[@class='im-ct-menu-title im-ct-contacts-header' and text()='Contacts']")
        SEARCH_TEXTBOX = (By.XPATH, "//input[contains(@class, 'im-pa-mc-contactsearch-searchTextBox')]")
        NO_CONTACTS_FOUND_ALERT = (By.XPATH, '//*[contains(@class, "im-pa-mc-no-contacts")]')
        TABLE_BODY = (By.XPATH, '//*[contains(@class, "im-pa-mc-contact-tablebody")]')
        ROWS = (By.CSS_SELECTOR, f"[class*='{'im-table-row ng-star-inserted'}']")
        SUBJECT_CLASS = (By.CSS_SELECTOR, f"[class*='{'im-pa-mc-contact-textname'}']")
        CONTEXT_AREA = (By.CSS_SELECTOR, f"[class*='{'im-ct-items ps'}']")
        CONTACT_TABLE = (By.CSS_SELECTOR, f"[class*='{'im-pa-mc-mycontainer'}']")
        SCROLL_CLASS = (By.CSS_SELECTOR, f"[class*='{'ps--active-y'}']")
        SCROLLBAR = (By.CSS_SELECTOR, f"[class*='{'ps__thumb-y'}']")
        ROW_ACTIONS = (By.CLASS_NAME, "im-pa-mc-hoveroverlayer-hoverButtonContainer")
        DC_HEADER = (By.XPATH, "//*[contains(@class, 'im-dctab-headerroot')]")
        CHAT_EDITOR = (By.CSS_SELECTOR, f"[class*='{'im-da-ch-textarea editable-element'}']")
        DC_TAB_AREA_LAYOUT = (By.XPATH, "//*[contains(@class, 'im-td-directchattablayout-root')]")
        DC_TAB_LAYOUT = (By.XPATH, "//*[contains(@class, 'im-td-directchattablayout-body')]")
        DC_MESSAGE_AREA = (By.XPATH, "//*[contains(@class, 'im-da-ch-marginTop')]")
        DC_MESSAGE = (By.CSS_SELECTOR, "[class*='im-da-ch-msg-text ng-star-inserted']")
        DC_FILE = (By.CSS_SELECTOR, "[class*='attachImgIcon-fileName']")
        INPUT_AREA = (By.CLASS_NAME, "im-da-ch-inputcontainer")
        SVG_ICONS = (By.TAG_NAME, "svg")
        SVG_ICON_CONTACT_ROW_ACTION = (By.TAG_NAME, "im-sc-svgicon")
        OVERLAY_CONTAINER = (By.CSS_SELECTOR, f"[class*='im-td-detailsoverlay-container']")
        BLOCK_BUTTON = (By.CSS_SELECTOR, "[class*='im-pa-mc-contactedit-deleteBtn']")
        DIALOG_CONTAINER = (By.CSS_SELECTOR, f"[class*='{'im-pa-mc-blockchatcontactalert-confirmationDialog'}']")
        YES_BUTTON = (By.XPATH, "//button[contains(., 'Yes')]")
        DC_CONTACTS_UNDER_DIRECT_CHAT = (By.CLASS_NAME, "im-ct-contacts-pinned")
        DC_CONTACTS_AREA = (By.CSS_SELECTOR, f"[class*='{'im-ct-pinnedcontacts-contactcontainer'}']")
        DC_CONTACT_NAME_AREA = (By.CSS_SELECTOR, f"[class*='{'im-sc-participant-myChatContact'}']")
        MINI_CONTACT_LIST_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-cm-sh-sharelist-list'}']")  # Updated from im-pa-mc-minicontactlist-itemlist
        CONTACT_LIST_OVERLAY = (By.CSS_SELECTOR, "[class*='im-sc-participant-myChatContact']")
        MINI_CONTACT_CONTAINER_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-cm-sh-sharelist-container'}']")  # Updated from im-pa-mc-minicontactlist-container
        MINI_CONTACT_CONTAINER_MAIN_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-pa-sh-mpw-body'}']")
        ADD_CONTACT_LIST_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-shareitems-contacttable'}']")
        SCROLL_AREA_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'ps__rail-y'}']")  # Updated from ps--active-y
        SCROLL_BAR_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'ps__thumb-y'}']")
        CONTACT_CLICK_OVERLAY = (By.CSS_SELECTOR, 'button[type="button"]')
        ADD_INVITE_BUTTON_DIRECT_CHAT = (By.CSS_SELECTOR, f"[class*='{'im-ct-contacts-invitationstatus'}']")
        SEARCH_CHAT_BUTTON = (By.CSS_SELECTOR, f"[class*='{'im-pa-iv-clariti-contacts-section'}']")
        SEARCH_TEXT_BOX = (By.XPATH, "//input[contains(@class, 'im-uc-searchinput')]")
        CHAT_BUTTON = (By.CSS_SELECTOR, f"[class*='{'invite-buttons'}']")
        CHECKBOX_SELECTION_OVERLAY = (By.CSS_SELECTOR, f"[class*='{'im-td-item-checkbox'}']")
        ADD_CONTACT_BUTTON = (By.CSS_SELECTOR, f"[class*='{'im-shareitems-sharebtn'}']")
        PAYMENT_UPGRADE_CONTAINER = (By.CSS_SELECTOR, f"[class*='{'im-sh-paymentupgrade-container'}']")
        SVG_ICON = (By.TAG_NAME, "im-sc-svgicon")
        DC_TAB_HEADER = (By.CSS_SELECTOR, f"[class*='im-dctab-headerroot']")

    class HomePage:
        HOMEPAGE_UI = (By.CLASS_NAME, "im-floatingdlg-section-people.im-app-leftside-pane")
        IMPROPER_LOGOUT_ALERT = (By.XPATH, '//span[contains(text(),"Yes")]')
        NEW_CONVERSATION_BUTTON = (By.XPATH, ".//*[contains(text(), 'New Conversation')]")
        NEW_CONVERSATION_MAIL_STRIP_HEADER = (By.CSS_SELECTOR, f"[class*='{'im-tc-startnewcommstrip'}']")
        DETAIL_VIEW_HEADER = (By.CSS_SELECTOR, f"[class*='im-td-cdrivetablayout-header']")
        CONVERSATION_SUBJECT_TEXT_BOX = (By.CSS_SELECTOR, f"[class*='{'im-da-th-subject-input'}']")
        START_CONVERSATION_BUTTON = (By.CSS_SELECTOR, f"[class*='{'im-da-th-startConversationButton'}']")
        GO_BACK_HOME_ICON = (By.XPATH, "//*[contains(@class,'im-td-cdrive-previousbreadcrumb')]")
        GO_BACK_ICON = (By.CSS_SELECTOR, f"[class*='im-td-cdrive-backaction-container']")
        PROFILE_NAME_CONTAINER = (By.CLASS_NAME, "im-np-hm-userNameSpan")
        LOGOUT_AREA = (By.CLASS_NAME, "imLogoutPreference")
        LOGOUT = (By.XPATH, ".//*[contains(text(), 'Logout')]")
        LOGIN_PAGE_VERIFICATION = (By.CLASS_NAME, "im-au-custom-heading")
        CONTEXTS_AREA = (By.CSS_SELECTOR, f"[class*='{'im-ct-items ps'}']")
        MAIL_COUNT = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Mail ']"
                                "//span[contains(@class, 'im-ct-cdrivemenu-unreadcount')]")
        HOME_COUNT = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Home ']"
                                "//span[contains(@class, 'im-ct-cdrivemenu-unreadcount')]")
        CONTEXT_AREA = (By.CSS_SELECTOR, f"[class*='{'im-ct-items ps'}']")
        TRASH_TAB = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Trash']")
        HOME_TAB = (By.CLASS_NAME, "im-ct-cdrivemenu")
        CONVERSATION_TAB = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Conversations ']")
        OK_LETS_GO_BUTTON = (By.XPATH, "//button/span[contains(text(), ' Ok, Let's go ')]")
        NEW_DIRECT_CHAT_BUTTON = (By.CLASS_NAME, "im-ct-add-directchat-layout")
        PINNED_CONTACTS_AREA = (By.CLASS_NAME, "im-ct-contacts-pinned")
        DC_CONTACT_DIRECT_CHAT = (By.CSS_SELECTOR, f"[class*='{'im-ct-pinnedcontacts-contactcontainer'}']")
        DC_CONTACT_NAME_DIRECT_CHAT = (By.CSS_SELECTOR, f"[class*='{'im-sc-participantName im-sc-participant-myChatContact'}']")
        DC_CONTACT_GREEN_INDICATOR_DIRECT_CHAT = (By.CSS_SELECTOR, f"[class*='{'im-ct-pinnedcontacts-status ng-star'}']")
        NAVIGATION_PANEL_CHAT = (By.CSS_SELECTOR, f"[class*='{'BgChatCall'}']")
        NAVIGATION_PANEL_COMPOSE_MAIL = (By.CSS_SELECTOR, f"[class*='{'BgComposeMail'}']")
        NAVIGATION_PANEL_MOVE_MAIL = (By.CSS_SELECTOR, f"[class*='{'BgMail im-td-operation-icon'}']")
        NAVIGATION_PANEL_ADD_MAIL_SOURCE = (By.CSS_SELECTOR, f"[class*='{'BgExternalMail'}']")
        NAVIGATION_PANEL_FILES = (By.CSS_SELECTOR, f"[class*='{'BgFiles im-td-operation-icon'}']")
        NAVIGATION_PANEL_ADD_CLOUD_SOURCE = (By.CSS_SELECTOR, f"[class*='{'BgCloudStorage'}']")
        NAVIGATION_PANEL_FEEDS = (By.CSS_SELECTOR, f"[class*='{'BgFeeds im-td-operation-icon'}']")
        NAVIGATION_PANEL_ADD_FEEDS_SOURCE = (By.CSS_SELECTOR, f"[class*='{'BgSocialMedia'}']")
        NAVIGATION_PANEL_TODO = (By.CSS_SELECTOR, f"[class*='{'BgScheduleToDo'}']")
        NAVIGATION_PANEL_EVENT = (By.CSS_SELECTOR, f"[class*='{'BgScheduleEvent'}']")
        NAVIGATION_PANEL_SCHEDULE_CALL = (By.CSS_SELECTOR, f"[class*='{'BgScheduleCall'}']")
        CONVERSATION_CONTINUOUS_VIEW = (By.CSS_SELECTOR, "[class*='im-da-th-continuousTimelineviewRoot']")
        ITEM_LIST_CONTINUOUS_VIEW = (By.CSS_SELECTOR, "[class*='im-da-cm-timeline-ItemsContainer']")
        MESSAGE_CONTINUES_VIEW = (By.CSS_SELECTOR, "[class*='im-da-ch-msg-text ng-star-inserted']")
        CHAT_ITEM_OPERATION_ICON = (By.CSS_SELECTOR, "[class*='im-da-threadOperations']")
        CHAT_ITEM_SHOW_ACTION_BUTTON = (By.CSS_SELECTOR, "[class*='im-da-th-settingsBtn']")
        OVERLAY_PANE = (By.CSS_SELECTOR, "[class*='cdk-overlay-pane']")
        SHOW_ACTIONS_OPERATIONS = (By.CSS_SELECTOR, "[class*='im-da-th-oper']")
        IP_CHAT_CONVERSATION_CONTINUOUS_VIEW = (By.CSS_SELECTOR, "[class*='im-da-ch-ipdetails-scrollbody ps']")
        ACTIVE_CHATS_UNDER_HOME = (By.CLASS_NAME, "im-ct-contacts-activechats")
        ACTIVE_CHAT_ITEM_UNDER_HOME = (By.CSS_SELECTOR, f"[class*='{'im-ct-contacts-activechat ng'}']")
        ACTIVE_CHAT_SUBJECT_CLASS = (By.CLASS_NAME, "im-ct-chatSubject")
        ACTIVE_CHAT_CLOSE_ICON = (By.CSS_SELECTOR, f"[class*='{'im-ct-close ng'}']")
        COMPOSE_MAIL_ACTION_BUTTON = (By.CSS_SELECTOR, f"[class*='{'BcCompose'}']")
        OVERLAY_CONTAINER = (By.CSS_SELECTOR, f"[class*='{'im-td-detailsoverlay-container'}']")
        DETAIL_VIEW = (By.CSS_SELECTOR, f"[class*='{'im-td-cdrivetablayout-root'}']")
        POP_OUT_MAIL_DRAFT = (By.CSS_SELECTOR, f"[class*='im-td-overlayPopout-icon']")
        TABLE_BODY = (By.XPATH, '//*[contains(@id, "cdk-drop-list-")]')
        ROWS = (By.CSS_SELECTOR, f"[class*='{'im-td-cdrive-row isDiscussion'}']")
        DATE_SEPARATOR_ROW = (By.CSS_SELECTOR, f"[class*='{'im-td-Dateseparator'}']")
        SUBJECT_CLASS = (By.CSS_SELECTOR, f"[class*='{'im-td-cdrivetablecell-textname'}']")

    class SignUpPage:
        USERNAME = (By.XPATH, "//input[@name='somethingAutofillDoesntKnow']")
        PASSWORD = (By.XPATH, "//*[@class='im-au-login-password']/input")
        SIGNUP_BUTTON = (By.CSS_SELECTOR, "button.im-au-custom-login-btn")

        YANDEX_USERID_TEXTBOX = (By.XPATH, "//input[@id='passp-field-login']")
        YANDEX_LOGIN_BUTTON = (By.XPATH, "//button[@type='submit']")
        YANDEX_PASSWORD_TEXTBOX = (By.XPATH, "//input[@id='passp-field-passwd']")
        YANDEX_FORGOT_PASSWORD_LINK = (By.ID, "field:link-passwd")
        YANDEX_HOMEPAGE = (By.CLASS_NAME, "PSHeader-Left")
        YANDEX_INBOX_ITEMS = (By.CSS_SELECTOR, ".ns-view-container-desc.mail-MessagesList.js-messages-list")
        YANDEX_INBOX_ITEM_ROW = (By.XPATH, "//*[@class='mail-MessageSnippet-Content']")
        FROM_ADDRESS_CLASS = (By.CSS_SELECTOR,
                              ".mail-MessageSnippet-Item.mail-MessageSnippet-Item_sender.js-message-snippet-sender")
        FROM_ADDRESS = (By.CLASS_NAME, "mail-MessageSnippet-FromText")
        SIGN_UP_BUTTON_MAIL = (By.XPATH, "//a[normalize-space()='Click here to set up your password']")
        ONBOARDING_CONTAINER = (By.CLASS_NAME, "im-td-onboarding-options-container")
        INVITE_LATER = (By.CLASS_NAME, "im-td-onboardingoption-text1")
        CONTINUE_BUTTON = (By.XPATH, "//button/span[contains(text(), 'Continue')]")

    class LoginPage:
        USERNAME = (By.XPATH, "//input[@name='somethingAutofillDoesntKnow']")
        PASSWORD = (By.XPATH, "//*[@class='im-au-login-password']/input")
        LOGIN_BUTTON = (By.CSS_SELECTOR, "button.im-au-custom-login-btn")
        HOMEPAGE_UI = (By.XPATH, "//div[@class='im-floatingdlg-section-people im-app-leftside-pane']")
        IMPROPER_LOGOUT_ALERT = (By.XPATH, '//span[contains(text(),"Yes")]')
        ONBOARDING_UI = (By.XPATH, "//div[@class='im-td-onboarding-options-container']")
        ONBOARDING_UI_LATER_OPTION = (By.CSS_SELECTOR, f"[class*='im-td-onboardingoption-dialog dialog1']")
        ONBOARDING_UI_NOW_OPTION = (By.CSS_SELECTOR, f"[class*='im-td-onboardingoption-dialog dialog2']")
        ONBOARDING_UI_SELECTION_TEXT = (By.CLASS_NAME, "im-td-onboardingoption-text1")
        LOGIN_WITH_MICROSOFT_BUTTON = (By.XPATH, "//*[@class='im-au-btemplate-socialText' and text()='Login with Microsoft']")
        LOGIN_WITH_GOOGLE_BUTTON = (By.XPATH, "//*[@class='im-au-btemplate-socialText' and text()='Login with Google']")
        LOGIN_WITH_YAHOO_BUTTON = (By.XPATH, "//*[@class='im-au-btemplate-socialText' and text()='Login with Yahoo']")
        LOGIN_WITH_APPLE_BUTTON = (By.XPATH, "//*[@class='im-au-btemplate-socialText' and text()='Login with Apple']")
        PROFILE_NAME_CONTAINER = (By.CLASS_NAME, "im-np-hm-userNameSpan")
        LOGOUT = (By.XPATH, ".//*[contains(text(), 'logout')]")
        MICROSOFT_EMAIL = (By.XPATH, "//input[@type='email']")
        MICROSOFT_EMAIL_NEXT = (By.XPATH, "//input[@type='submit']")
        MICROSOFT_PASSWORD = (By.XPATH, "//input[@name='passwd']")
        MICROSOFT_PASSWORD_NEXT = (By.XPATH, "//input[@type='submit']")
        MICROSOFT_SIGNIN_UI = (By.XPATH, "//*[@text()='Stay signed in?']")
        MICROSOFT_SIGNIN_BUTTON = (By.XPATH, "//input[@type='submit']")
        GOOGLE_EMAIL = (By.XPATH, "//input[@id='identifierId']")
        GOOGLE_EMAIL_NEXT = (By.ID, "identifierNext")
        GOOGLE_PASSWORD = (By.XPATH, "//input[@type='password']")
        GOOGLE_PASSWORD_NEXT = (By.ID, "passwordNext")
        YAHOO_EMAIL = (By.XPATH, "//input[@id='login-username']")
        YAHOO_EMAIL_NEXT = (By.XPATH, "//input[@name='signin']")
        YAHOO_PASSWORD = (By.XPATH, "//input[@id='login-passwd']")
        YAHOO_PASSWORD_NEXT = (By.XPATH, "//button[@id='login-signin']")
        YANDEX_USERID_TEXTBOX = (By.XPATH, "//input[@id='passp-field-login']")
        YANDEX_LOGIN_BUTTON = (By.XPATH, "//button[@type='submit']")
        YANDEX_PASSWORD_TEXTBOX = (By.XPATH, "//input[@id='passp-field-passwd']")
        YANDEX_FORGOT_PASSWORD_LINK = (By.ID, "field:link-passwd")
        YANDEX_HOMEPAGE = (By.CLASS_NAME, "PSHeader-Left")
        YANDEX_INBOX_ITEMS = (By.CSS_SELECTOR, ".ns-view-container-desc.mail-MessagesList.js-messages-list")
        YANDEX_INBOX_ITEM_ROW = (By.XPATH, "//*[@class='mail-MessageSnippet-Content']")
        FROM_ADDRESS_CLASS = (By.CSS_SELECTOR,
                              ".mail-MessageSnippet-Item.mail-MessageSnippet-Item_sender.js-message-snippet-sender")
        FROM_ADDRESS = (By.CLASS_NAME, "mail-MessageSnippet-FromText")
        SIGN_UP_BUTTON_MAIL = (By.XPATH, "//a[normalize-space()='Click here to set up your password']")
        SIGNUP_HREF_LINKS = (By.CSS_SELECTOR, "a[href]")
        ENTER_NAME_CUSTOM_SIGNUP = (By.CSS_SELECTOR, "input[placeholder='Enter name']")
        ENTER_PASSWORD_CUSTOM_SIGNUP = (By.CSS_SELECTOR, "input[placeholder='Enter password']")
        ENTER_RE_ENTER_CUSTOM_SIGNUP = (By.CSS_SELECTOR, "input[placeholder='Re-enter password']")
        SIGNUP_BUTTON = (By.XPATH, "//*[@class='im-au-custom-proceed-button' and text()=' Sign up ']")
        ONBOARDING_CONTAINER = (By.CLASS_NAME, "im-td-onboarding-options-container")
        INVITE_LATER = (By.CSS_SELECTOR, f"[class*='im-td-onboardingoption-dialog dialog1']")
        INVITE_NOW = (By.CSS_SELECTOR, f"[class*='im-td-onboardingoption-dialog dialog2']")
        INVITE_OPTION_TEXT = (By.CLASS_NAME, "im-td-onboardingoption-text1")
        CONTINUE_BUTTON = (By.XPATH, "//button/span[contains(text(), 'Continue')]")
        LETS_GO_BUTTON = (By.CSS_SELECTOR, f"[class*='im-da-letsgobutton']")

    class MailDraftPage:
        COMPOSE_MAIL_ICON = (By.CSS_SELECTOR, "[class*='im-tc-startnewcommstrip']")
        SUBJECT_FIELD = (By.XPATH, "//input[contains(@class,'im-da-dr-subjectInput')]")
        TO_FIELD_TEXTBOX = (By.CSS_SELECTOR, "[class*='im-da-dr-toEmailInput']")
        BODY_AREA = (By.CLASS_NAME, "claritioriginalcontent")
        SEND_BUTTON = (By.XPATH, '//button/span[contains(text(),"Send")]')
        SEND_BUTTON_CLASS = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerSendBtn']")
        MAT_BUTTON_DISABLED = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerSendBtn mdc-button']")
        MAIL_TAB = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Mail ']")
        DETAIL_VIEW_HEADER_TEXT = (By.CSS_SELECTOR, "[class*='im-td-cdrivetabheader-drive']")
        DETAIL_VIEW = (By.CSS_SELECTOR, "[class*='im-td-cdrivetablayout-root']")
        CLARITI_FULL_VIEW = (By.CSS_SELECTOR, "[class*='im-app-left-splitter']")
        CLOSE_ICON_DRAFT = (By.CSS_SELECTOR, "[class*='im-ct-close']")
        CONFIRMATION_BUTTON_CLASS = (By.CSS_SELECTOR, "[class*='im-sc-confirmationdialog-Btn'] span")
        CONFIRMATION_BUTTON = (By.CSS_SELECTOR, "[class*='im-sc-confirmationdialog-Btn mat']")
        YES_BUTTON_TO_CLOSE_CONFIRMATION = (By.XPATH, "//button[contains(., 'Yes')]")
        DRAFT_AREA = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainer']")
        DRAFT_LAYOUT_CONTEXTS_AREA = (By.CSS_SELECTOR, "[class*='im-ct-emaildraft-layout']")
        DRAFT_MAIL_SVG_ICON_CONTEXTS_AREA = (By.CSS_SELECTOR, "[class*='im-ct-ipitem-icon']")
        DRAFT_TEXT_CONTEXTS_AREA = (By.CSS_SELECTOR, "[class*='im-ct-activechat-initiator']")
        DRAFT_SUBJECT_CONTEXTS_AREA = (By.CSS_SELECTOR, "[class*='im-ct-activechat-subject']")
        MAIL_DRAFT_HEADER_TEXT = (By.CSS_SELECTOR, "[class*='im-td-maildraft-headingdefault']")
        DRAFT_TO_CC_BCC_FIELD = (By.CSS_SELECTOR, "[class*='im-da-dr-recipientItem']")
        DRAFT_TO_CC_BCC_LABEL_TEXT = (By.CSS_SELECTOR, "[class*='im-da-cm-labelPrefix']")
        DRAFT_TO_CC_BCC_ADD_PLUS_ICON = (By.CSS_SELECTOR, "[class*='im-da-dr-contactsIconContainer']")
        DRAFT_CC_BCC_ATTACHMENT_ICON_AREA = (By.CSS_SELECTOR, "[class*='im-da-dr-CCRecipientsAttachFiles']")
        DRAFT_CC_BUTTON = (By.CSS_SELECTOR, "[class*='im-da-dr-showCcMail']")
        DRAFT_BCC_BUTTON = (By.CSS_SELECTOR, "[class*='im-da-dr-showBccMail']")
        DRAFT_ATTACHMENT_ICON = (By.CSS_SELECTOR, "[class*='im-da-dr-AttachFilesIcon']")
        BODY_CONTENT = (By.CLASS_NAME, "claritioriginalcontent")
        MAIL_DRAFT_BODY = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerBody']")
        SHOW_EDITOR_TOOLBAR_ICON = (By.CSS_SELECTOR, "[class*='im-da-dr-draftEditorPullDownArrowContainer']")
        EDITOR_TOOLBAR = (By.CSS_SELECTOR, "[class*='im-da-dr-editorToolbar']")
        EDITOR_TOOLBAR_FONT_NAME = (By.CSS_SELECTOR, "[class*='im-da-dr-fontNameSel']")
        EDITOR_TOOLBAR_FONT_SIZE = (By.CSS_SELECTOR, "[class*='im-da-dr-fontSizeSel']")
        EDITOR_TOOL_BOLD = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarBold']")
        EDITOR_TOOL_ITALIC = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarItalic']")
        EDITOR_TOOL_STRIKE = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarStrike']")
        EDITOR_TOOL_UNDER_LINE = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarUnderline']")
        EDITOR_TOOL_COLOUR = (By.CSS_SELECTOR, "[class*='im-da-dr-fontColorSel']")
        EDITOR_TOOL_COLOUR_ICON = (By.CSS_SELECTOR, "[class*='im-da-dr-fontColorIcon']")
        EDITOR_TOOL_COLOUR_LIST_DIALOG = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarFontColorList']")
        EDITOR_TOOL_COLOUR_LIST = (By.TAG_NAME, "li")
        EDITOR_TOOL_COLOUR_LIST_ITEM = (By.TAG_NAME, "a")
        EDITOR_TOOL_BULLET_LIST = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarBulletList']")
        EDITOR_TOOL_NUMBER_LIST = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarNumberList']")
        EDITOR_TOOL_REDUCE_INDENT = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarReduceIndent']")
        EDITOR_TOOL_INDENT = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarIndent']")
        EDITOR_TOOL_LEFT_ALIGN = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarJustLeft']")
        EDITOR_TOOL_CENTER_ALIGN = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarJustCenter']")
        EDITOR_TOOL_RIGHT_ALIGN = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarJustRight']")
        EDITOR_TOOL_MORE_ICON = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarInsertTitle']")
        EDITOR_TOOL_INSERT_IMAGE_OVERLAY = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarInsertPicture']")
        EDITOR_TOOL_INSERT_HYPERLINK_OVERLAY = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarInsertLink']")
        EDITOR_TOOL_INSERT_SIGNATURE_OVERLAY = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarSignature']")
        EDITOR_TOOL_REPLY_TO_OVERLAY = (By.CSS_SELECTOR, "[class*='im-da-dr-draftToolBarReplyTo']")
        BOLD_TAG = (By.TAG_NAME, "b")
        ITALIC_TAG = (By.TAG_NAME, "i")
        UNDER_LINE_TAG = (By.TAG_NAME, "u")
        STRIKE_TAG = (By.TAG_NAME, "strike")
        BULLET_LIST_TAG = (By.TAG_NAME, "ul")
        NUMBERED_LIST_TAG = (By.TAG_NAME, "ol")
        INDENT_TAG = (By.TAG_NAME, "blockquote")
        IMAGE_TAG = (By.TAG_NAME, "img")
        OVERLAY_ACTION_CLASS = (By.CSS_SELECTOR, "[class*='mat-mdc-menu-content']")
        BUTTON_TAG = (By.TAG_NAME, "button")
        DRAFT_HEADER_AREA = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerDraftHeader']")
        TO_CC_BCC_LABEL_ICON_AREA = (By.CSS_SELECTOR, "[class*='im-da-cm-labelPrefix']")
        TO_CC_BCC_LABEL_PARENT = (By.XPATH, "./ancestor::mat-chip-list")
        TO_CC_BCC_LABEL_ICON = (By.CSS_SELECTOR, "[class*='im-da-dr-contactsIconContainer']")
        OVERLAY_CONTAINER = (By.CSS_SELECTOR, "[class='cdk-overlay-container']")
        OVERLAY_PANE = (By.CSS_SELECTOR, "[class='cdk-overlay-pane']")
        ADD_PARTICIPANT_DIALOG = (By.CSS_SELECTOR, "[class*='im-da-dr-emailtoPos']")
        ADD_PARTICIPANT_DIALOG_HEADER_TEXT = (By.CSS_SELECTOR, "[class*='im-da-cm-title']")
        SEARCH_CONTACT_TEXT_BOX = (By.CSS_SELECTOR, "[class*='im-pa-mc-minicontactlist-searchinput']")
        ADD_MAIL_TO_SEND_MAILS_TEXT_CLASS = (By.CSS_SELECTOR, "[class*='im-da-dr-warningText']")
        DRAFT_FOOTER_SEND_BUTTON_AREA = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerSendBtnArea']")
        ADD_MAIL_TO_SEND_MAILS_TEXT_HYPERLINK = (By.CSS_SELECTOR, "[class*='im-da-dr-hyperlink']")
        SEND_INFO_DRAFT_AREA = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerSendMsgInfo']")
        INFO_MESSAGE_CLASS = (By.CSS_SELECTOR, "[class='im-da-dr-draftcontainerSendMsgInfoPopUp']")
        RECIPIENT_ERROR_INFO = (By.CSS_SELECTOR, "[class*='im-da-dr-messagelistErrorMessages']")
        SUBJECT_ERROR_INFO = (By.CSS_SELECTOR, "[class*='im-da-dr-messagelistWarningMessages']")
        ADD_MAIL_TO_SEND_MAILS_TEXT = "Add mail account to send mails"
        INTEGRATION_BREADCRUMB_HEADER = (By.CSS_SELECTOR, "[class*='im-np-up-profiledetail-breadcrumb-container']")
        SEND_MAIL_ENABLED_PREMIUM_SUBSCRIPTION_TEXT = "Send mail is enabled with Premium subscription"
        REMOVE_CONTACT_ICON = (By.CSS_SELECTOR, "[class*='im-da-cm-remove']")
        UPGRADE_ALERT_DIALOG = (By.CSS_SELECTOR, "[class*='im-sh-paymentupgrade-text']")
        UPGRADE_DIALOG_CLOSE_ICON = (By.CSS_SELECTOR, "[class*='im-da-cm-mccloseicon']")
        OVERLAY_CLOSE_CLICK_ANYWHERE = (By.CSS_SELECTOR, "[class*='cdk-overlay-container']")
        OVERLAY_MAIL_DRAFT = (By.CSS_SELECTOR, "[class*='im-td-cdrive-detailsOverlay']")
        ADD_CONTACT_OVERLAY = (By.CSS_SELECTOR, "[class*='im-td-shareemailitem']")
        MAXIMUM_10_FILES_ALERT = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerInvalidAttachMessageContainer']")
        MAXIMUM_10_FILES_ALERT_INFO_ICON = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerAttachInfoIcon']")
        FILE_ATTACHMENT_AREA = (By.CSS_SELECTOR, "[class*='im-da-dr-draftcontainerAttachmentList']")
        FILE_ATTACHMENTS = (By.CSS_SELECTOR, "[class*='im-da-cm-fileContainer']")
        FILE_ATTACHMENT_NAME = (By.CSS_SELECTOR, "[class*='attachImgIcon-fileName']")
        FILE_ATTACHMENT_DELETE_ICON = (By.CSS_SELECTOR, "[class*='im-da-cm-deleteIconClass']")
        FILE_ATTACHMENT_SVG_ICON = (By.CSS_SELECTOR, "[class*='im-da-cm-imageContainer']")
        FILE_ATTACHMENT_CANCEL_UPLOAD = (By.CSS_SELECTOR, "[class*='im-da-cm-cancelUploadIcon']")
        OVERLAY_TOOLTIP = (By.CSS_SELECTOR, "[class*='mdc-tooltip__surface-animation']")
        OVERLAY_DIALOG = (By.CSS_SELECTOR, "[class*='im-td-detailsoverlay-container']")
        OVERLAY_DIALOG_TITLE = (By.CSS_SELECTOR, "[class*='im-shareitems-title']")
        CLOSE_ICON_OVERLAY = (By.CSS_SELECTOR, "[class*='im-td-overlayClose-icon']")
        OVERLAY_SEARCH_TEXTBOX = (By.CSS_SELECTOR, "[class*='im-cm-share-searchTextBox']")
        MAIL_DRAFT_LAYOUT = (By.CSS_SELECTOR, "[class*='im-td-maildrafttablayout-root']")
        TABLE_BODY = (By.XPATH, '//*[contains(@class, "im-pa-mc-contact-tablebody")]')
        ROWS = (By.CSS_SELECTOR, "[class*='im-table-row ng-star-inserted']")
        SUBJECT_CLASS = (By.CSS_SELECTOR, "[class*='im-pa-mc-contact-textname']")
        NO_CONTACTS_FOUND_ALERT = (By.XPATH, '//*[contains(@class, "im-pa-mc-no-contacts")]')
        CONTACT_TABLE = (By.CSS_SELECTOR, "[class*='im-shareitems-contacttable']")
        FOCUSED_TEXTBOX_HYPERLINK = (By.CSS_SELECTOR, "[class*='mdc-floating-label--float-above']")
        HYPERLINK_URL_TEXT_TEXTBOX = (By.CSS_SELECTOR, "[class*='im-da-dr-urltext'] input")
        HYPERLINK_URL_TEXTBOX = (By.CSS_SELECTOR, "[class*='im-da-dr-url n'] input")
        HYPERLINK_INSERT_BUTTON = (By.CSS_SELECTOR, "[class*='im-da-dr-okBtn']")
        HYPERLINK_PREVIEW_LINK = (By.CSS_SELECTOR, "[class*='im-da-dr-hyperLink']")
        HYPERLINK_ERROR_NOT_A_VALID_URL = (By.CSS_SELECTOR, "[class*='mat-mdc-form-field-error']")
        HYPERLINK_DIALOG_CLOSE = (By.CSS_SELECTOR, "[class*='im-da-cm-mcclose']")
        MINI_CONTACT_LIST_OVERLAY = (By.CSS_SELECTOR, "[class*='im-cm-sh-sharelist-list']")
        CONTACT_LIST_OVERLAY = (By.CSS_SELECTOR, "[class*='im-sc-participant-myChatContact']")
        MINI_CONTACT_CONTAINER_OVERLAY = (By.CSS_SELECTOR, "[class*='im-cm-sh-sharelist-container']")
        MINI_CONTACT_CONTAINER_MAIN_OVERLAY = (By.CSS_SELECTOR, "[class*='im-pa-sh-mpw-body']")
        SCROLL_AREA_OVERLAY = (By.CSS_SELECTOR, "[class*='ps__rail-y']")
        SCROLL_BAR_OVERLAY = (By.CSS_SELECTOR, "[class*='ps__thumb-y']")
        CONTACT_CLICK_OVERLAY = (By.CSS_SELECTOR, 'button[type="button"]')
        HYPERLINK_DIALOG = (By.CSS_SELECTOR, "[class*='im-da-dr-parentContainer']")
        SIGNATURE_DIALOG = (By.CSS_SELECTOR, "[class*='im-da-dr-signatureDraftEditor']")
        CHECKBOX_AREA = (By.CSS_SELECTOR, "[class*='im-da-dr-signatureCheckBox']")
        CHECKBOX_INPUT = (By.CSS_SELECTOR, "[class*='mdc-checkbox__native-control']")
        REPLY_TO_TEXTBOX = (By.CSS_SELECTOR, "[class*='im-da-dr-replyto'] input")
        REPLY_TO_MSG_DRAFT = (By.CSS_SELECTOR, "[class*='im-da-dr-replyToMsg']")
        REPLY_TO_MSG_DRAFT_LABEL_TEXT = "Reply for this email will be sent to"
        MAIL_WILL_BE_SENT_USING = (By.CSS_SELECTOR, "[class*='im-da-dr-fromidComp']")
        MAIL_WILL_BE_SENT_USING_EMAIL_ID = (By.CSS_SELECTOR, "[class*='im-da-dr-selectedMailId']")
        MAIL_WILL_BE_SENT_USING_EMAIL_ID_DROP_DOWN = (By.CSS_SELECTOR, "[class*='im-da-dr-selectFromEmailIDs']")
        DRAFT_BODY_TEXT = (By.CSS_SELECTOR, "[class*='claritioriginalcontent'] div")
        DRAFT_BODY_TEXT_TAB = (By.CSS_SELECTOR, "[class*='claritioriginalcontent'] br")
        DRAFT_BODY = (By.CSS_SELECTOR, "[class*='claritioriginalcontent']")

    class MailPage:
        CONTEXTS_AREA = (By.CSS_SELECTOR, "[class*='im-app-leftside-pane']")
        HOME_TAB_FOCUS = (By.XPATH, ".//*[contains(text(), 'New Conversation')]")
        NEW_STRIP = (By.CSS_SELECTOR, "[class*='im-tc-startnewcommstrip']")
        TABLE_BODY = (By.XPATH, '//*[contains(@id, "cdk-drop-list-")]')
        ROWS = (By.CSS_SELECTOR, "[class*='im-td-cdrive-row']")
        ROWS_LOADING = (By.CSS_SELECTOR, "[class*='im-td-cdrive-row row-loading']")
        SUBJECT_CLASS = (By.CSS_SELECTOR, "[class*='im-td-cdrivetablecell-textname']")
        PARTICIPANT_CLASS = (By.CSS_SELECTOR, "[class*='im-sc-ll-participant-host']")
        CONTEXT_AREA = (By.CSS_SELECTOR, "[class*='im-ct-items ps']")
        MAIL_TAB = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Mail ']")
        MAIL_TAB_TAG = (By.XPATH, "//im-ct-emails")
        OPERATIONS_WRAPPER = (By.CSS_SELECTOR, "[class*='im-da-th-operationsWrapper']")
        GO_BACK_ICON = (By.XPATH, "//*[contains(@class,'im-td-cdrive-previousbreadcrumb')]")
        HEADER_AREA = (By.CSS_SELECTOR, "[class*='im-da-cm-headeroperationsRoot']")
        OPERATION_ICON = (By.CSS_SELECTOR, "[class*='im-da-cm-headeroperationsIcon']")
        ROUTE_DIALOG = (By.CLASS_NAME, "im-td-cdrivedetails-routeDialog")
        ADD_BUTTON_SPAM = (By.CSS_SELECTOR, "[class*='routingBasicAddBtn']")
        MAIL_TAB_DETAIL_AREA = (By.CLASS_NAME, "im-td-cdrivedetailsRoot")
        THREAD_AREA = (By.CSS_SELECTOR, "[class*='im-da-th-ThreadBody-email']")
        SPAM_TEXT = (By.CSS_SELECTOR, "[class*='im-da-em-spamText']")
        SINGLETON_ICONS = (By.CSS_SELECTOR, "[class*='im-da-singletonoperations']")
        UN_SPAM_RESTORE_ICON = (By.CSS_SELECTOR, "[class*='im-da-th-trashOperationIcon']")
        TABLE_EXPLORER = (By.CSS_SELECTOR, "[class*='im-td-cdrivetablayout-table']")
        DELETE_ICON_ROW_ACTION = (By.CSS_SELECTOR, "[class*='im-da-cm-drive-DeleteDrive']")
        DELETE_TOOLTIP_MAIN_CONTAINER = (By.CLASS_NAME, "cdk-overlay-container")
        DELETE_BUTTON_TOOLTIP_EXPECTED = "Mail belonging to a mail chain cannot be deleted"
        DELETE_BUTTON_TOOLTIP = (By.XPATH, "//*[contains(@id, 'cdk-overlay-')]/mat-tooltip-component/div")
        MAIL_COUNT = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Mail ']"
                                "//span[contains(@class, 'im-ct-cdrivemenu-unreadcount')]")
        HOME_COUNT = (By.XPATH, "//div[@class='im-ct-menu-title' and text()='Home ']"
                                "//span[contains(@class, 'im-ct-cdrivemenu-unreadcount')]")
        MAIL_TAB_UI = (By.XPATH, ".//*[contains(text(), 'Compose Mail')]")
        TRASH_TAB_FILTER = (By.CSS_SELECTOR, "[class*='im-td-definedfilter-container']")
        TRASH_TAB_HEADER = (By.XPATH, "//div[@class='im-td-cdrivetabheader-drive' and text()=' Trash ']")
        TABLE_ROW_LOADING = (By.CLASS_NAME, "loading-container ng-star-inserted")
        OVERLAY_MAIL_DRAFT = (By.CSS_SELECTOR, "[class*='im-td-cdrive-detailsOverlay']")
        DETAIL_VIEW_HEADER_TEXT = (By.CSS_SELECTOR, "[class*='im-td-cdrivetabheader-drive']")
        DETAIL_VIEW = (By.CSS_SELECTOR, "[class*='im-td-cdrivetablayout-root']")
        CLARITI_FULL_VIEW = (By.CSS_SELECTOR, "[class*='im-app-left-splitter']")
        BRING_MAILS_ICON = (By.CSS_SELECTOR, "[class*='im-ct-email-subtitle']")
        OVERLAY_CONTAINER = (By.CSS_SELECTOR, "[class*='im-td-detailsoverlay-container']")
        CONFIGURED_EMAIL_BRING_MAILS_OVERLAY = (By.CSS_SELECTOR, "[class*='im-td-configuredcardcontainer']")
        GOOGLE_MAIL_CARD = (By.XPATH, "//*[@class='card-name' and contains(text(),'Google')]")
        MICROSOFT_MAIL_CARD = (By.XPATH, "//*[@class='card-name' and contains(text(),'Microsoft 365')]")
        OUTLOOK_MAIL_CARD = (By.XPATH, "//*[@class='card-name' and contains(text(),'Outlook')]")
        MICROSOFT_EMAIL = (By.XPATH, "//input[@type='email']")
        MICROSOFT_EMAIL_NEXT = (By.XPATH, "//input[@type='submit']")
        MICROSOFT_PASSWORD = (By.XPATH, "//input[@name='passwd']")
        MICROSOFT_PASSWORD_NEXT = (By.XPATH, "//input[@type='submit']")
        MICROSOFT_SIGNIN_UI = (By.XPATH, "//*[@text()='Stay signed in?']")
        MICROSOFT_SIGNIN_BUTTON = (By.XPATH, "//input[@type='submit']")
        OVERLAY_MAIL_CONFIGURE_LOADING = (By.CSS_SELECTOR, "[class*='im-da-cm-progress-statusIconContainer ng-star-inserted']")
        OVERLAY_MAIL_ITEM_ROW = (By.CSS_SELECTOR, "[class*='im-td-cdrive-row']")
        OVERLAY_MAIL_ITEM_TABLE_BODY = (By.CSS_SELECTOR, "[class*='im-td-cdrive-tablebody']")
        DATE_SEPERATOR_ROW = (By.CSS_SELECTOR, "[class*='im-td-Dateseparator']")
        CHECK_BOX_CLASS = (By.CSS_SELECTOR, "[class*='im-td-cdrivetablecell-checkbox']")
        BRING_SELECTED_MAILS_BUTTON = (By.CSS_SELECTOR, "[class*='ok_button']")
        OVERLAY_HEADER_TEXT = (By.CSS_SELECTOR, "[class*='breadcrumb-title']")
        OVERLAY_CLOSE_ICON = (By.CSS_SELECTOR, "[class*='im-td-overlayClose-icon']")
        CONNECT_HEADER_BUTTON_CLASS = (By.CSS_SELECTOR, "[class*='im-np-cm-integrationslist-optionheader']")
        INTEGRATION_CARD = (By.XPATH, ".//ancestor::im-np-cm-integrationscard")
        CONNECT_BUTTON = (By.CSS_SELECTOR, "[class*='im-np-cm-integrationslist-connectbtn']")
        PROFILE_NAME_CLASS = (By.CLASS_NAME, "im-np-hm-userNameSpan")
        MAIL_PREFERENCE = (By.CSS_SELECTOR, "[class*='imEmailPreference']")
        ADD_MAIL_CONFIGURE_BUTTON = (By.XPATH, '//button/span[contains(text(),"Add ")]')
        CONFIGURED_EMAIL_CARD = (By.CSS_SELECTOR, "[class*='im-np-cm-integrations-cardForAccount']")
        MAIL_CONFIGURED_UI = (By.CSS_SELECTOR, "[class*='im-np-ep-configured-container']")
        REMOVE_ACCOUNT_BUTTON = (By.CSS_SELECTOR, "[class*='im-rm-removeButton']")
        YES_BUTTON_TO_REMOVE_ACCOUNT = (By.XPATH, "//button[contains(., 'Yes')]")
        MAIL_PREFERENCES_MAIN_UI = (By.CSS_SELECTOR, "[class*='im-np-ep-manageAccountcontainer']")
